/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Aug 19 22:17:01 2018. */

#include "gtfs-realtime.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const transit_realtime_FeedHeader_Incrementality transit_realtime_FeedHeader_incrementality_default = transit_realtime_FeedHeader_Incrementality_FULL_DATASET;
const bool transit_realtime_FeedEntity_is_deleted_default = false;
const transit_realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship transit_realtime_TripUpdate_StopTimeUpdate_schedule_relationship_default = transit_realtime_TripUpdate_StopTimeUpdate_ScheduleRelationship_SCHEDULED;
const transit_realtime_VehiclePosition_VehicleStopStatus transit_realtime_VehiclePosition_current_status_default = transit_realtime_VehiclePosition_VehicleStopStatus_IN_TRANSIT_TO;
const transit_realtime_Alert_Cause transit_realtime_Alert_cause_default = transit_realtime_Alert_Cause_UNKNOWN_CAUSE;
const transit_realtime_Alert_Effect transit_realtime_Alert_effect_default = transit_realtime_Alert_Effect_UNKNOWN_EFFECT;


const pb_field_t transit_realtime_FeedMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, transit_realtime_FeedMessage, header, header, &transit_realtime_FeedHeader_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, transit_realtime_FeedMessage, entity, header, &transit_realtime_FeedEntity_fields),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_FeedMessage, extensions, entity, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_FeedHeader_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, transit_realtime_FeedHeader, gtfs_realtime_version, gtfs_realtime_version, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedHeader, incrementality, gtfs_realtime_version, &transit_realtime_FeedHeader_incrementality_default),
    PB_FIELD(  3, UINT64  , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedHeader, timestamp, incrementality, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_FeedHeader, extensions, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_FeedEntity_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, transit_realtime_FeedEntity, id, id, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedEntity, is_deleted, id, &transit_realtime_FeedEntity_is_deleted_default),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedEntity, trip_update, is_deleted, &transit_realtime_TripUpdate_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedEntity, vehicle, trip_update, &transit_realtime_VehiclePosition_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_FeedEntity, alert, vehicle, &transit_realtime_Alert_fields),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_FeedEntity, extensions, alert, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TripUpdate_fields[7] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, transit_realtime_TripUpdate, trip, trip, &transit_realtime_TripDescriptor_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, transit_realtime_TripUpdate, stop_time_update, trip, &transit_realtime_TripUpdate_StopTimeUpdate_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate, vehicle, stop_time_update, &transit_realtime_VehicleDescriptor_fields),
    PB_FIELD(  4, UINT64  , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate, timestamp, vehicle, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate, delay, timestamp, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TripUpdate, extensions, delay, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TripUpdate_StopTimeEvent_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, transit_realtime_TripUpdate_StopTimeEvent, delay, delay, 0),
    PB_FIELD(  2, INT64   , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate_StopTimeEvent, time, delay, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate_StopTimeEvent, uncertainty, time, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TripUpdate_StopTimeEvent, extensions, uncertainty, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TripUpdate_StopTimeUpdate_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, transit_realtime_TripUpdate_StopTimeUpdate, stop_sequence, stop_sequence, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate_StopTimeUpdate, arrival, stop_sequence, &transit_realtime_TripUpdate_StopTimeEvent_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate_StopTimeUpdate, departure, arrival, &transit_realtime_TripUpdate_StopTimeEvent_fields),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_TripUpdate_StopTimeUpdate, stop_id, departure, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_TripUpdate_StopTimeUpdate, schedule_relationship, stop_id, &transit_realtime_TripUpdate_StopTimeUpdate_schedule_relationship_default),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TripUpdate_StopTimeUpdate, extensions, schedule_relationship, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_VehiclePosition_fields[11] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, transit_realtime_VehiclePosition, trip, trip, &transit_realtime_TripDescriptor_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, position, trip, &transit_realtime_Position_fields),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, current_stop_sequence, position, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, current_status, current_stop_sequence, &transit_realtime_VehiclePosition_current_status_default),
    PB_FIELD(  5, UINT64  , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, timestamp, current_status, 0),
    PB_FIELD(  6, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, congestion_level, timestamp, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_VehiclePosition, stop_id, congestion_level, 0),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, vehicle, stop_id, &transit_realtime_VehicleDescriptor_fields),
    PB_FIELD(  9, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_VehiclePosition, occupancy_status, vehicle, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_VehiclePosition, extensions, occupancy_status, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_Alert_fields[9] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, transit_realtime_Alert, active_period, active_period, &transit_realtime_TimeRange_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, transit_realtime_Alert, informed_entity, active_period, &transit_realtime_EntitySelector_fields),
    PB_FIELD(  6, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_Alert, cause, informed_entity, &transit_realtime_Alert_cause_default),
    PB_FIELD(  7, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_Alert, effect, cause, &transit_realtime_Alert_effect_default),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_Alert, url, effect, &transit_realtime_TranslatedString_fields),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_Alert, header_text, url, &transit_realtime_TranslatedString_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_Alert, description_text, header_text, &transit_realtime_TranslatedString_fields),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_Alert, extensions, description_text, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TimeRange_fields[4] = {
    PB_FIELD(  1, UINT64  , OPTIONAL, STATIC  , FIRST, transit_realtime_TimeRange, start, start, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, transit_realtime_TimeRange, end, start, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TimeRange, extensions, end, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_Position_fields[7] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, transit_realtime_Position, latitude, latitude, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, transit_realtime_Position, longitude, latitude, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, transit_realtime_Position, bearing, longitude, 0),
    PB_FIELD(  4, DOUBLE  , OPTIONAL, STATIC  , OTHER, transit_realtime_Position, odometer, bearing, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, transit_realtime_Position, speed, odometer, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_Position, extensions, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TripDescriptor_fields[8] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, transit_realtime_TripDescriptor, trip_id, trip_id, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_TripDescriptor, start_time, trip_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_TripDescriptor, start_date, start_time, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, transit_realtime_TripDescriptor, schedule_relationship, start_date, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_TripDescriptor, route_id, schedule_relationship, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, transit_realtime_TripDescriptor, direction_id, route_id, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TripDescriptor, extensions, direction_id, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_VehicleDescriptor_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, transit_realtime_VehicleDescriptor, id, id, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_VehicleDescriptor, label, id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_VehicleDescriptor, license_plate, label, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_VehicleDescriptor, extensions, license_plate, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_EntitySelector_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, transit_realtime_EntitySelector, agency_id, agency_id, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_EntitySelector, route_id, agency_id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, transit_realtime_EntitySelector, route_type, route_id, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, transit_realtime_EntitySelector, trip, route_type, &transit_realtime_TripDescriptor_fields),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_EntitySelector, stop_id, trip, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_EntitySelector, extensions, stop_id, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TranslatedString_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, transit_realtime_TranslatedString, translation, translation, &transit_realtime_TranslatedString_Translation_fields),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TranslatedString, extensions, translation, 0),
    PB_LAST_FIELD
};

const pb_field_t transit_realtime_TranslatedString_Translation_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, transit_realtime_TranslatedString_Translation, text, text, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, transit_realtime_TranslatedString_Translation, language, text, 0),
    PB_FIELD(1000, EXTENSION, OPTIONAL, CALLBACK, OTHER, transit_realtime_TranslatedString_Translation, extensions, language, 0),
    PB_LAST_FIELD
};










/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(transit_realtime_FeedMessage, header) < 65536 && pb_membersize(transit_realtime_FeedEntity, trip_update) < 65536 && pb_membersize(transit_realtime_FeedEntity, vehicle) < 65536 && pb_membersize(transit_realtime_FeedEntity, alert) < 65536 && pb_membersize(transit_realtime_TripUpdate, trip) < 65536 && pb_membersize(transit_realtime_TripUpdate, vehicle) < 65536 && pb_membersize(transit_realtime_TripUpdate_StopTimeUpdate, arrival) < 65536 && pb_membersize(transit_realtime_TripUpdate_StopTimeUpdate, departure) < 65536 && pb_membersize(transit_realtime_VehiclePosition, trip) < 65536 && pb_membersize(transit_realtime_VehiclePosition, vehicle) < 65536 && pb_membersize(transit_realtime_VehiclePosition, position) < 65536 && pb_membersize(transit_realtime_Alert, url) < 65536 && pb_membersize(transit_realtime_Alert, header_text) < 65536 && pb_membersize(transit_realtime_Alert, description_text) < 65536 && pb_membersize(transit_realtime_EntitySelector, trip) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_transit_realtime_FeedMessage_transit_realtime_FeedHeader_transit_realtime_FeedEntity_transit_realtime_TripUpdate_transit_realtime_TripUpdate_StopTimeEvent_transit_realtime_TripUpdate_StopTimeUpdate_transit_realtime_VehiclePosition_transit_realtime_Alert_transit_realtime_TimeRange_transit_realtime_Position_transit_realtime_TripDescriptor_transit_realtime_VehicleDescriptor_transit_realtime_EntitySelector_transit_realtime_TranslatedString_transit_realtime_TranslatedString_Translation)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for transit_realtime_TranslatedString_Translation.extensions is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
