/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Aug 19 22:17:01 2018. */

#include "nyct-subway.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TripReplacementPeriod_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, TripReplacementPeriod, route_id, route_id, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, TripReplacementPeriod, replacement_period, route_id, &transit_realtime_TimeRange_fields),
    PB_LAST_FIELD
};

const pb_field_t NyctFeedHeader_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, NyctFeedHeader, nyct_subway_version, nyct_subway_version, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, NyctFeedHeader, trip_replacement_period, nyct_subway_version, &TripReplacementPeriod_fields),
    PB_LAST_FIELD
};

const pb_field_t NyctTripDescriptor_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, NyctTripDescriptor, train_id, train_id, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, NyctTripDescriptor, is_assigned, train_id, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, NyctTripDescriptor, direction, is_assigned, 0),
    PB_LAST_FIELD
};

const pb_field_t NyctStopTimeUpdate_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, NyctStopTimeUpdate, scheduled_track, scheduled_track, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, NyctStopTimeUpdate, actual_track, scheduled_track, 0),
    PB_LAST_FIELD
};

typedef struct {
    NyctFeedHeader nyct_feed_header;
} nyct_feed_header_struct;

static const pb_field_t nyct_feed_header_field = 
      PB_FIELD(1001, MESSAGE , OPTEXT, STATIC  , FIRST, nyct_feed_header_struct, nyct_feed_header, nyct_feed_header, &NyctFeedHeader_fields);

const pb_extension_type_t nyct_feed_header = {
    NULL,
    NULL,
    &nyct_feed_header_field
};

typedef struct {
    NyctTripDescriptor nyct_trip_descriptor;
} nyct_trip_descriptor_struct;

static const pb_field_t nyct_trip_descriptor_field = 
      PB_FIELD(1001, MESSAGE , OPTEXT, STATIC  , FIRST, nyct_trip_descriptor_struct, nyct_trip_descriptor, nyct_trip_descriptor, &NyctTripDescriptor_fields);

const pb_extension_type_t nyct_trip_descriptor = {
    NULL,
    NULL,
    &nyct_trip_descriptor_field
};

typedef struct {
    NyctStopTimeUpdate nyct_stop_time_update;
} nyct_stop_time_update_struct;

static const pb_field_t nyct_stop_time_update_field = 
      PB_FIELD(1001, MESSAGE , OPTEXT, STATIC  , FIRST, nyct_stop_time_update_struct, nyct_stop_time_update, nyct_stop_time_update, &NyctStopTimeUpdate_fields);

const pb_extension_type_t nyct_stop_time_update = {
    NULL,
    NULL,
    &nyct_stop_time_update_field
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TripReplacementPeriod, replacement_period) < 65536 && pb_membersize(nyct_feed_header_struct, nyct_feed_header) < 65536 && pb_membersize(nyct_trip_descriptor_struct, nyct_trip_descriptor) < 65536 && pb_membersize(nyct_stop_time_update_struct, nyct_stop_time_update) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TripReplacementPeriod_NyctFeedHeader_NyctTripDescriptor_NyctStopTimeUpdate)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for nyct_stop_time_update_struct.nyct_stop_time_update is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
